/score/create/boxMesh boxMesh
#
/score/mesh/boxSize 10.5 10.5 0.25 cm
/score/mesh/translate/xyz 0. 0. 110.1561 cm
/score/mesh/nBin 201 201 1
#
/score/quantity/energyDeposit eDep
#
/score/close

/score/list
/run/printProgress 1

/GB04/biasing/setSplittingFactor 80
/GB04/biasing/biasPrimaryOnly false
/GB04/biasing/biasOnlyOnce    false

/run/beamOn 10000000

/score/dumpQuantityToFile boxMesh eDep EnergyDeposition.txt